controller_list:
  - name: fake_gantry axis_controller
    type: $(arg fake_execution_type)
    joints:
      - bridge_joint
      - carriage_joint
initial:  # Define initial robot poses per group
#  - group: gantry axis
#    pose: home

  []